version: "3"
services:
  db:
    image: "postgres:13.3-alpine"
    ports:
      - 5432:5432
    volumes:
      - ./db/init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./mounts/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DATABASE_USERNAME=booster_user
      - DATABASE_PASSWORD=booster_pass
      - DATABASE_NAME=booster
